-- Create msg_email table for storing inbox and sent emails
CREATE TABLE IF NOT EXISTS `msg_email` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '邮件ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID（邮件所属用户）',
  `direction` VARCHAR(20) NOT NULL COMMENT '邮件方向：inbound-收件, outbound-发件',
  `subject` VARCHAR(500) DEFAULT NULL COMMENT '邮件主题',
  `from_email` VARCHAR(255) NOT NULL COMMENT '发件人邮箱',
  `from_name` VARCHAR(255) DEFAULT NULL COMMENT '发件人名称',
  `to_email` VARCHAR(500) NOT NULL COMMENT '收件人邮箱',
  `cc_email` TEXT COMMENT '抄送邮箱',
  `content` LONGTEXT COMMENT '邮件内容(HTML)',
  `preview` VARCHAR(500) DEFAULT NULL COMMENT '纯文本内容预览',
  `has_attachment` TINYINT(1) DEFAULT 0 COMMENT '是否有附件',
  `attachments` TEXT COMMENT '附件信息(JSON格式)',
  `is_read` TINYINT(1) DEFAULT 0 COMMENT '是否已读',
  `is_starred` TINYINT(1) DEFAULT 0 COMMENT '是否星标',
  `folder` VARCHAR(50) DEFAULT 'inbox' COMMENT '文件夹：inbox/starred/sent/drafts/archive/spam/trash',
  `labels` VARCHAR(500) DEFAULT NULL COMMENT '标签(JSON数组)',
  `customer_id` BIGINT DEFAULT NULL COMMENT '关联客户ID',
  `email_settings_id` BIGINT DEFAULT NULL COMMENT '关联邮箱设置ID',
  `message_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '邮件接收/发送时间',
  `deleted` TINYINT(1) DEFAULT 0 COMMENT '删除标记：0-未删除, 1-已删除',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建者',
  `created_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_direction` (`direction`),
  KEY `idx_folder` (`folder`),
  KEY `idx_message_time` (`message_time`),
  KEY `idx_customer_id` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='邮件存储表';
